Configurable API endpoint prefix
cybercog/youtrack-rest-php pull request #43
Opened 2019-10-17 13:35 UTC by asteisiunas

Simple solution

2019-10-17 15:29 UTC, antonkomarev commented
Resolves #42

2019-10-17 15:35 UTC, antonkomarev requested changes

2019-10-17 15:35 UTC, antonkomarev commented on src/Client/YouTrackClient.php
> +        $this->endpointPathPrefix = $prefix;
I think it would be better to remove `/` characters from start and end of the `$prefix` variable.

```php
$this->endpointPathPrefix = trim($prefix, '/');
```

2019-10-17 15:36 UTC, antonkomarev commented
Thank you for the contribution, @asteisiunas!

2019-10-18 02:51 UTC, asteisiunas commented on src/Client/YouTrackClient.php
> +        $this->endpointPathPrefix = $prefix;
Why? It's config, not an input from a user.

2019-10-18 12:53 UTC, antonkomarev commented on src/Client/YouTrackClient.php
> +        $this->endpointPathPrefix = $prefix;
You are right.

2019-10-18 12:54 UTC, merged